import type { Metadata } from "next";
import { Bungee_Inline } from "next/font/google";
import AdminNavbar from "@/app/admin/_components/AdminNavbar";

export const dynamic = "force-dynamic";

const bungee = Bungee_Inline({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${bungee.className} flex flex-col min-h-screen bg-white`}>
      <AdminNavbar />
      <main className="flex-1"> {children}</main>
    </div>
  );
}
